name: Publish

on:
    push:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the source code
              uses: actions/checkout@v3
            - name: Lint (sqflint)
              uses: arma-actions/sqflint@master
              continue-on-error: true

    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the source code
              uses: actions/checkout@v3
            - name: Setup HEMTT
              uses: arma-actions/hemtt@v1
            - name: Run HEMTT build
              run: hemtt release
            - name: Extract Zipped Mod
              run: unzip releases/braf_factions-latest.zip -d releases
            - uses: arma-actions/workshop-upload@v1
              with:
                  appId: '107410'
                  itemId: ${{ secrets.STEAM_WORKSHOP_ITEM_ID }}
                  contentPath: releases/@braf_factions
                  changelog: 'Update'
              env:
                  STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
                  STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
            - name: Discord notification
              uses: tsickert/discord-webhook@v5.3.0
              with:
                  webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
                  username: Saci
                  avatar-url: https://scontent.fpoa33-1.fna.fbcdn.net/v/t1.6435-9/123089286_2720897204844263_4695033759855672932_n.jpg?_nc_cat=102&ccb=1-7&_nc_sid=810d5f&_nc_eui2=AeHYW_2fgJH67ADthIzboTmE_dndmKxNqvb92d2YrE2q9oc1UC5FYvsZ-cUbwpH19bbxxRLaBL159Gtrl1Ug8_dM&_nc_ohc=UeyYATHroS8AX9MnQDS&_nc_ht=scontent.fpoa33-1.fna&oh=00_AfD1hpwiRVRZXYafCTkpgEIX_ZyCHNKey4zoP6zsin_bMg&oe=655AAACE
                  embed-title: ${{ github.repository }} ATUALIZADO E PUBLICADO!
                  embed-url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'
                  embed-description: Commit ${{ github.sha }} - ${{ github.event.head_commit.message }} autorizado e mod (dev) atualizado no Steam Workshop!
                  embed-author-name: ${{ github.actor }}
                  embed-author-url: https://github.com/${{ github.actor }}
                  embed-author-icon-url: https://avatars.githubusercontent.com/${{ github.actor }}
                  embed-footer-icon-url: https://avatars.githubusercontent.com/${{ github.repository_owner }}
                  embed-footer-text: ${{ github.repository_owner }}
                  embed-color: 16515072
